# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'VitorGomes-mobile-test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VitorGomes-mobile-test
  
  pod 'Kingfisher', '~> 6.3'
  pod 'InitialsImageView', '~> 0.7'

  target 'VitorGomes-mobile-testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VitorGomes-mobile-testUITests' do
    # Pods for testing
  end

end
